"""Runtime data-source provenance for user-visible surfaces.

Every surface that reports numbers to a human must state where those numbers came from. The
governed Upstox V3 acquisition path in :mod:`quant_system.data.upstox` fails closed without a
bearer token, so a runtime with no credentials configured is necessarily running on generated
data. Naming that explicitly is the difference between a research tool and a misleading one.
"""

from __future__ import annotations

import os
from enum import StrEnum

from quant_system.data.market_data import UPSTOX_HISTORICAL_SOURCE

API_KEY_ENV_VAR = "UPSTOX_API_KEY"  # pragma: allowlist secret - variable name, not a value.
ACCESS_TOKEN_ENV_VAR = "UPSTOX_ACCESS_TOKEN"


class RuntimeDataSource(StrEnum):
    """Origin of the bars behind a reported result."""

    SYNTHETIC = "SYNTHETIC"
    UPSTOX_HISTORICAL = UPSTOX_HISTORICAL_SOURCE


SYNTHETIC_DISCLOSURE = (
    "Generated by SyntheticDataGenerator, not real market data. Figures below describe a "
    "deterministic random walk and carry no predictive or historical claim about any traded "
    "instrument."
)

UPSTOX_HISTORICAL_DISCLOSURE = (
    "Acquired from the Upstox V3 historical-candle API under the governed point-in-time "
    "acquisition contract."
)


def market_data_credentials_configured() -> bool:
    """Report whether a provider bearer token is present.

    Only presence is inspected. The token value is never read into a return value, logged, or
    stored, because that would put a live credential into evidence artifacts.
    """
    return bool(os.getenv(ACCESS_TOKEN_ENV_VAR, "").strip())


def describe(source: RuntimeDataSource) -> str:
    """Return the human-readable disclosure for a data source."""
    if source is RuntimeDataSource.SYNTHETIC:
        return SYNTHETIC_DISCLOSURE
    return UPSTOX_HISTORICAL_DISCLOSURE
