"""Quant Tearsheet Generator: Formats performance metrics and risk attribution."""

from __future__ import annotations

from typing import TYPE_CHECKING

from quant_system.analytics.metrics import QuantStats

if TYPE_CHECKING:
    from quant_system.backtest.engine import BacktestResult


class TearsheetGenerator:
    """Renders comprehensive, institutional-style quantitative tearsheets."""

    @staticmethod
    def generate_markdown(
        result: BacktestResult, stats: QuantStats, strategy_name: str = "QuantStrategy"
    ) -> str:
        md = []
        md.append(f"# Quant Performance Tearsheet: {strategy_name}")
        md.append("")
        md.append("## 1. Executive Summary")
        md.append("")
        md.append("| Metric | Value | Status / Quality Gate |")
        md.append("| :--- | :--- | :--- |")
        md.append(f"| **Initial Capital** | Rs. {result.initial_cash:,.2f} | Baseline |")
        md.append(f"| **Final Equity** | Rs. {result.final_equity:,.2f} | P&L Mark |")
        md.append(
            f"| **Total Net Return** | **{stats.total_return_pct:.2%}** | {'[+] Profitable' if stats.total_return_pct > 0 else '[-] Loss'} |"
        )
        md.append(f"| **CAGR (Annualized)** | **{stats.cagr_pct:.2%}** | Compounded Growth |")
        md.append(
            f"| **Total Friction Paid** | Rs. {result.total_friction_paid:,.2f} | STT + Turnover + Slippage |"
        )
        md.append("")
        md.append("## 2. Risk-Adjusted Return Profile")
        md.append("")
        md.append("| Risk Metric | Score | Industry Benchmark |")
        md.append("| :--- | :--- | :--- |")
        md.append(
            f"| **Sharpe Ratio (Rf=7%)** | **{stats.sharpe_ratio:.2f}** | {'[PASS] Excellent (>1.5)' if stats.sharpe_ratio >= 1.5 else '[PASS] Acceptable (>1.0)' if stats.sharpe_ratio >= 1.0 else '[WARN] Sub-par (<1.0)'} |"
        )
        md.append(f"| **Sortino Ratio** | **{stats.sortino_ratio:.2f}** | Downside Risk Adjusted |")
        md.append(f"| **Calmar Ratio** | **{stats.calmar_ratio:.2f}** | Return / Max Drawdown |")
        md.append(
            f"| **Annualized Volatility** | {stats.annualized_volatility:.2%} | Realized Volatility |"
        )
        md.append(
            f"| **Max Drawdown** | **{stats.max_drawdown_pct:.2%}** | {'[PASS] Controlled (<15%)' if stats.max_drawdown_pct <= 0.15 else '[ALERT] High Risk (>15%)'} |"
        )
        md.append(
            f"| **Max Drawdown Duration** | {stats.max_drawdown_duration_bars} bars | Recovery Length |"
        )
        md.append("")
        md.append("## 3. Trade Execution & Win Statistics")
        md.append("")
        md.append("| Trade Metric | Value | Notes |")
        md.append("| :--- | :--- | :--- |")
        md.append(f"| **Total Executed Fills** | {stats.total_trades} | Completed Orders |")
        md.append(f"| **Win Rate** | {stats.win_rate:.2%} | Profitable Closed Trades |")
        md.append(
            f"| **Profit Factor** | {stats.profit_factor:.2f} | Gross Profits / Gross Losses |"
        )
        md.append(
            f"| **Average Trade P&L** | Rs. {stats.avg_trade_pnl:,.2f} | Expectancy per closed trade |"
        )
        md.append("")
        md.append("---")
        md.append("*Generated by QuantOS Modular Engine. Exact Decimal reconciliation verified.*")
        return "\n".join(md)
