"""Release Manifest generation and validation engine for QuantOS Windows releases."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from quant_system import __version__


@dataclass(frozen=True)
class FileChecksum:
    """Cryptographic checksum and size metadata for an individual release artifact file."""

    relative_path: str
    sha256: str
    size_bytes: int


@dataclass(frozen=True)
class ReleaseManifest:
    """Complete cryptographic release manifest for QuantOS distribution."""

    app_name: str
    version: str
    git_commit_sha: str
    uv_lock_sha256: str
    build_timestamp: str
    target_os: str
    target_arch: str
    executable: str
    total_files: int
    total_bytes: int
    files: dict[str, dict[str, Any]]


@dataclass(frozen=True)
class ManifestValidationResult:
    """Result of validating a release bundle against its manifest."""

    is_valid: bool
    total_checked: int
    missing_files: list[str]
    corrupted_files: list[str]
    unmanifested_files: list[str]
    message: str


def compute_file_sha256(filepath: Path) -> str:
    """Computes SHA-256 hash of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def generate_release_manifest(
    bundle_dir: Path,
    git_commit_sha: str,
    uv_lock_sha256: str,
    version: str | None = None,
    executable_name: str = "quantos.exe",
    target_os: str = "windows",
    target_arch: str = "x86_64",
) -> ReleaseManifest:
    """Scans bundle directory and generates complete cryptographic release manifest."""
    if not bundle_dir.exists() or not bundle_dir.is_dir():
        raise FileNotFoundError(f"Bundle directory does not exist: {bundle_dir}")

    files_map: dict[str, dict[str, Any]] = {}
    total_bytes = 0
    total_files = 0

    # Ignored metadata files that are generated by or wrap the manifest
    excluded_names = {"release-manifest.json", "MANIFEST.sha256", "release.json"}

    for file_path in sorted(bundle_dir.rglob("*")):
        if file_path.is_file():
            rel_posix = file_path.relative_to(bundle_dir).as_posix()
            if file_path.name in excluded_names:
                continue

            file_hash = compute_file_sha256(file_path)
            file_size = file_path.stat().st_size
            files_map[rel_posix] = {
                "sha256": file_hash,
                "size_bytes": file_size,
            }
            total_bytes += file_size
            total_files += 1

    app_ver = version or __version__
    return ReleaseManifest(
        app_name="QuantOS",
        version=app_ver,
        git_commit_sha=git_commit_sha,
        uv_lock_sha256=uv_lock_sha256,
        build_timestamp=datetime.now(UTC).isoformat(),
        target_os=target_os,
        target_arch=target_arch,
        executable=executable_name,
        total_files=total_files,
        total_bytes=total_bytes,
        files=files_map,
    )


def write_release_manifest(bundle_dir: Path, manifest: ReleaseManifest) -> tuple[Path, Path, Path]:
    """Writes release-manifest.json, MANIFEST.sha256, and release.json into the bundle directory."""
    bundle_dir.mkdir(parents=True, exist_ok=True)

    # 1. Full JSON Manifest
    manifest_json_path = bundle_dir / "release-manifest.json"
    with open(manifest_json_path, "w", encoding="utf-8") as f:
        json.dump(asdict(manifest), f, indent=2, sort_keys=False)

    # 2. Standard sha256sum format MANIFEST.sha256
    manifest_sha_lines = [
        f"{meta['sha256']}  {path}" for path, meta in sorted(manifest.files.items())
    ]
    manifest_sha_path = bundle_dir / "MANIFEST.sha256"
    manifest_sha_path.write_text("\n".join(manifest_sha_lines) + "\n", encoding="utf-8")

    # 3. Compact release.json metadata
    release_info = {
        "app_name": manifest.app_name,
        "version": manifest.version,
        "git_commit_sha": manifest.git_commit_sha,
        "uv_lock_sha256": manifest.uv_lock_sha256,
        "build_date": manifest.build_timestamp,
        "target_platform": f"{manifest.target_os}-{manifest.target_arch}",
        "total_files": manifest.total_files,
        "total_bytes": manifest.total_bytes,
        "executable": manifest.executable,
    }
    release_json_path = bundle_dir / "release.json"
    with open(release_json_path, "w", encoding="utf-8") as f:
        json.dump(release_info, f, indent=2)

    return manifest_json_path, manifest_sha_path, release_json_path


def validate_release_bundle(
    bundle_dir: Path,
    manifest_path: Path | None = None,
    allow_unmanifested: bool = False,
) -> ManifestValidationResult:
    """Validates the cryptographic integrity of a release bundle against its manifest."""
    target_manifest_path = manifest_path or (bundle_dir / "release-manifest.json")
    if not target_manifest_path.exists():
        return ManifestValidationResult(
            is_valid=False,
            total_checked=0,
            missing_files=[],
            corrupted_files=[],
            unmanifested_files=[],
            message=f"Manifest not found: {target_manifest_path}",
        )

    try:
        with open(target_manifest_path, encoding="utf-8") as f:
            manifest_data = json.load(f)
    except Exception as err:
        return ManifestValidationResult(
            is_valid=False,
            total_checked=0,
            missing_files=[],
            corrupted_files=[],
            unmanifested_files=[],
            message=f"Failed to parse manifest: {err}",
        )

    expected_files = manifest_data.get("files", {})
    missing: list[str] = []
    corrupted: list[str] = []

    checked_count = 0
    for rel_path, meta in expected_files.items():
        actual_path = bundle_dir / Path(rel_path)
        checked_count += 1
        if not actual_path.exists():
            missing.append(rel_path)
            continue

        actual_size = actual_path.stat().st_size
        if actual_size != meta.get("size_bytes"):
            corrupted.append(
                f"{rel_path} (size mismatch: expected {meta.get('size_bytes')}, got {actual_size})"
            )
            continue

        actual_sha = compute_file_sha256(actual_path)
        if actual_sha != meta.get("sha256"):
            corrupted.append(
                f"{rel_path} (hash mismatch: expected {meta.get('sha256')}, got {actual_sha})"
            )

    unmanifested: list[str] = []
    excluded_names = {"release-manifest.json", "MANIFEST.sha256", "release.json"}
    if not allow_unmanifested:
        for p in bundle_dir.rglob("*"):
            if p.is_file():
                rel_posix = p.relative_to(bundle_dir).as_posix()
                if p.name not in excluded_names and rel_posix not in expected_files:
                    unmanifested.append(rel_posix)

    is_valid = len(missing) == 0 and len(corrupted) == 0 and len(unmanifested) == 0
    if is_valid:
        msg = "Release bundle verified successfully."
    else:
        msg = (
            f"Integrity check failed: {len(missing)} missing, "
            f"{len(corrupted)} corrupted, {len(unmanifested)} unmanifested."
        )

    return ManifestValidationResult(
        is_valid=is_valid,
        total_checked=checked_count,
        missing_files=missing,
        corrupted_files=corrupted,
        unmanifested_files=unmanifested,
        message=msg,
    )
