import logging
import sqlite3
from typing import List, Dict, Any
from quant_system.shariah.db.session import get_db_connection
from quant_system.shariah.db.init_db import init_db
from quant_system.shariah.services.screener_service import (
    check_sector_compliance,
    evaluate_company_shariah,
)

logger = logging.getLogger(__name__)

RAW_COMPANIES_DATA: List[Dict[str, Any]] = [
    # -------------------------------------------------------------
    # 1. SHARIAH COMPLIANT - IT SERVICES & TECHNOLOGY
    # -------------------------------------------------------------
    {
        "ticker": "TCS.NS",
        "symbol": "TCS",
        "isin": "INE467B01029",
        "bse_code": "532540",
        "company_name": "Tata Consultancy Services Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Consulting",
        "business_summary": "Global leader in IT services, digital transformation, cognitive business operations, and enterprise cloud solutions.",
        "current_price": 4210.50,
        "market_cap": 1523400.0,
        "avg_36m_market_cap": 1385400.0,
        "shares_outstanding": 3618000000,
        "pe_ratio": 31.2,
        "pb_ratio": 14.8,
        "dividend_yield": 0.0275,
        "last_dividend_per_share": 116.0,
        "total_assets": 142340.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 7970.0,
        "total_debt": 7970.0,
        "cash_and_bank": 11250.0,
        "current_investments": 14500.0,
        "total_cash_and_investments": 25750.0,
        "total_receivables": 38920.0,
        "total_inventories": 0.0,
        "current_liabilities": 41200.0,
        "operating_revenue": 240893.0,
        "other_income": 3950.0,
        "total_revenue": 244843.0,
        "interest_income": 1420.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 1420.0,
        "filing_date": "2024-04-12",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 18 - Lease Liabilities under Ind AS 116",
        "cash_note_ref": "Note 12 - Cash, Bank Balances & Liquid Funds",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Note 24 - Interest Income on Bank Deposits",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "INFY.NS",
        "symbol": "INFY",
        "isin": "INE009A01021",
        "bse_code": "500209",
        "company_name": "Infosys Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Consulting",
        "business_summary": "Next-generation digital services and consulting facilitating enterprise cloud and AI-driven transformation.",
        "current_price": 1890.25,
        "market_cap": 784200.0,
        "avg_36m_market_cap": 682000.0,
        "shares_outstanding": 4148000000,
        "pe_ratio": 29.4,
        "pb_ratio": 9.1,
        "dividend_yield": 0.0245,
        "last_dividend_per_share": 46.0,
        "total_assets": 105800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 5600.0,
        "total_debt": 5600.0,
        "cash_and_bank": 14200.0,
        "current_investments": 12800.0,
        "total_cash_and_investments": 27000.0,
        "total_receivables": 31200.0,
        "total_inventories": 0.0,
        "current_liabilities": 28400.0,
        "operating_revenue": 153670.0,
        "other_income": 3210.0,
        "total_revenue": 156880.0,
        "interest_income": 1160.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 1160.0,
        "filing_date": "2024-04-18",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 17 - Leases",
        "cash_note_ref": "Note 10 - Cash & Cash Equivalents",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 22 - Other Income (Interest on Term Deposits)",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "HCLTECH.NS",
        "symbol": "HCLTECH",
        "isin": "INE860A01027",
        "bse_code": "532281",
        "company_name": "HCL Technologies Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Infrastructure",
        "business_summary": "Global technology company specializing in digital engineering, cloud architecture, and modern application services.",
        "current_price": 1780.0,
        "market_cap": 482900.0,
        "avg_36m_market_cap": 348500.0,
        "shares_outstanding": 2713000000,
        "pe_ratio": 28.5,
        "pb_ratio": 7.2,
        "dividend_yield": 0.031,
        "last_dividend_per_share": 52.0,
        "total_assets": 88400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 520.0,
        "lease_liabilities": 3480.0,
        "total_debt": 4000.0,
        "cash_and_bank": 9400.0,
        "current_investments": 8100.0,
        "total_cash_and_investments": 17500.0,
        "total_receivables": 20400.0,
        "total_inventories": 120.0,
        "current_liabilities": 22100.0,
        "operating_revenue": 109913.0,
        "other_income": 1420.0,
        "total_revenue": 111333.0,
        "interest_income": 720.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 720.0,
        "filing_date": "2024-04-26",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Borrowings & Leases",
        "cash_note_ref": "Note 11 - Liquid Financial Assets",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 25 - Finance & Interest Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "WIPRO.NS",
        "symbol": "WIPRO",
        "isin": "INE075A01022",
        "bse_code": "507685",
        "company_name": "Wipro Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Consulting",
        "business_summary": "Leading technology services and consulting enterprise focused on high-assurance cognitive computing and hyper-automation.",
        "current_price": 545.0,
        "market_cap": 284900.0,
        "avg_36m_market_cap": 242000.0,
        "shares_outstanding": 5227000000,
        "pe_ratio": 24.8,
        "pb_ratio": 3.8,
        "dividend_yield": 0.009,
        "last_dividend_per_share": 5.0,
        "total_assets": 104200.0,
        "long_term_debt": 7100.0,
        "short_term_debt": 2400.0,
        "lease_liabilities": 2800.0,
        "total_debt": 12300.0,
        "cash_and_bank": 10200.0,
        "current_investments": 14800.0,
        "total_cash_and_investments": 25000.0,
        "total_receivables": 16900.0,
        "total_inventories": 80.0,
        "current_liabilities": 25400.0,
        "operating_revenue": 89760.0,
        "other_income": 2100.0,
        "total_revenue": 91860.0,
        "interest_income": 950.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 950.0,
        "filing_date": "2024-04-19",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Borrowings",
        "cash_note_ref": "Note 8 - Cash and Bank Balances",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Note 20 - Other Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "TECHM.NS",
        "symbol": "TECHM",
        "isin": "INE669C01036",
        "bse_code": "532755",
        "company_name": "Tech Mahindra Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Telecom Solutions",
        "business_summary": "Provider of digital transformation, network consulting, and next-generation business process solutions globally.",
        "current_price": 1620.0,
        "market_cap": 159200.0,
        "avg_36m_market_cap": 124500.0,
        "shares_outstanding": 982000000,
        "pe_ratio": 41.2,
        "pb_ratio": 5.4,
        "dividend_yield": 0.026,
        "last_dividend_per_share": 40.0,
        "total_assets": 44800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 980.0,
        "lease_liabilities": 1640.0,
        "total_debt": 2620.0,
        "cash_and_bank": 4800.0,
        "current_investments": 3200.0,
        "total_cash_and_investments": 8000.0,
        "total_receivables": 9200.0,
        "total_inventories": 0.0,
        "current_liabilities": 14100.0,
        "operating_revenue": 51996.0,
        "other_income": 820.0,
        "total_revenue": 52816.0,
        "interest_income": 460.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 460.0,
        "filing_date": "2024-04-25",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 16 - Financial Borrowings",
        "cash_note_ref": "Note 10 - Cash & Liquid Assets",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 23 - Other Non-Operating Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "LTIM.NS",
        "symbol": "LTIM",
        "isin": "INE214T01019",
        "bse_code": "540005",
        "company_name": "LTIMindtree Limited",
        "sector": "Information Technology",
        "industry": "IT Services & Consulting",
        "business_summary": "Global technology consulting and digital solutions enterprise formed by the merger of Larsen & Toubro Infotech and Mindtree.",
        "current_price": 5850.0,
        "market_cap": 173200.0,
        "avg_36m_market_cap": 142000.0,
        "shares_outstanding": 296000000,
        "pe_ratio": 36.8,
        "pb_ratio": 8.9,
        "dividend_yield": 0.012,
        "last_dividend_per_share": 65.0,
        "total_assets": 27400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 210.0,
        "lease_liabilities": 1850.0,
        "total_debt": 2060.0,
        "cash_and_bank": 2950.0,
        "current_investments": 4120.0,
        "total_cash_and_investments": 7070.0,
        "total_receivables": 6840.0,
        "total_inventories": 0.0,
        "current_liabilities": 7820.0,
        "operating_revenue": 35517.0,
        "other_income": 620.0,
        "total_revenue": 36137.0,
        "interest_income": 220.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 220.0,
        "filing_date": "2024-04-24",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 15 - Financial Liabilities",
        "cash_note_ref": "Note 9 - Cash & Bank Balances",
        "rec_note_ref": "Note 8 - Trade Receivables",
        "income_note_ref": "Note 21 - Other Non-Operating Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "PERSISTENT.NS",
        "symbol": "PERSISTENT",
        "isin": "INE262H01013",
        "bse_code": "533179",
        "company_name": "Persistent Systems Limited",
        "sector": "Information Technology",
        "industry": "Software Products & Engineering",
        "business_summary": "Pioneering digital engineering and enterprise modernization software specialist with strong cloud and AI capabilities.",
        "current_price": 5350.0,
        "market_cap": 82600.0,
        "avg_36m_market_cap": 59400.0,
        "shares_outstanding": 154000000,
        "pe_ratio": 58.2,
        "pb_ratio": 13.5,
        "dividend_yield": 0.007,
        "last_dividend_per_share": 35.0,
        "total_assets": 8940.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 560.0,
        "total_debt": 560.0,
        "cash_and_bank": 1120.0,
        "current_investments": 940.0,
        "total_cash_and_investments": 2060.0,
        "total_receivables": 1980.0,
        "total_inventories": 0.0,
        "current_liabilities": 2420.0,
        "operating_revenue": 9821.0,
        "other_income": 180.0,
        "total_revenue": 10001.0,
        "interest_income": 52.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 52.0,
        "filing_date": "2024-04-21",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Ind AS 116 Lease Obligations",
        "cash_note_ref": "Note 8 - Liquid Bank Balances",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Note 19 - Interest and Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "TATAELXSI.NS",
        "symbol": "TATAELXSI",
        "isin": "INE670A01012",
        "bse_code": "500408",
        "company_name": "Tata Elxsi Limited",
        "sector": "Information Technology",
        "industry": "Design & Engineering Technology",
        "business_summary": "Global design and technology services leader across automotive autonomous driving, media, healthcare, and rail transportation.",
        "current_price": 7320.0,
        "market_cap": 45600.0,
        "avg_36m_market_cap": 44100.0,
        "shares_outstanding": 62300000,
        "pe_ratio": 57.4,
        "pb_ratio": 16.8,
        "dividend_yield": 0.011,
        "last_dividend_per_share": 70.0,
        "total_assets": 3280.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 0.0,
        "total_debt": 0.0,
        "cash_and_bank": 920.0,
        "current_investments": 610.0,
        "total_cash_and_investments": 1530.0,
        "total_receivables": 790.0,
        "total_inventories": 0.0,
        "current_liabilities": 710.0,
        "operating_revenue": 3552.0,
        "other_income": 120.0,
        "total_revenue": 3672.0,
        "interest_income": 41.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 41.0,
        "filing_date": "2024-04-23",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Zero Debt Balance Sheet Disclosure",
        "cash_note_ref": "Note 7 - Liquid Cash & Term Deposits",
        "rec_note_ref": "Note 6 - Trade Receivables",
        "income_note_ref": "Note 17 - Deposit Interest",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 2. SHARIAH COMPLIANT - PHARMACEUTICALS & HEALTHCARE
    # -------------------------------------------------------------
    {
        "ticker": "SUNPHARMA.NS",
        "symbol": "SUNPHARMA",
        "isin": "INE044A01036",
        "bse_code": "524715",
        "company_name": "Sun Pharmaceutical Industries Limited",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals & Biotechnology",
        "business_summary": "India's largest specialty generic pharmaceutical company with presence across dermatology, ophthalmology, and oncology.",
        "current_price": 1780.0,
        "market_cap": 427100.0,
        "avg_36m_market_cap": 312000.0,
        "shares_outstanding": 2399000000,
        "pe_ratio": 42.1,
        "pb_ratio": 6.3,
        "dividend_yield": 0.008,
        "last_dividend_per_share": 13.5,
        "total_assets": 84200.0,
        "long_term_debt": 1420.0,
        "short_term_debt": 2850.0,
        "lease_liabilities": 1540.0,
        "total_debt": 5810.0,
        "cash_and_bank": 11800.0,
        "current_investments": 7400.0,
        "total_cash_and_investments": 19200.0,
        "total_receivables": 12400.0,
        "total_inventories": 11200.0,
        "current_liabilities": 19500.0,
        "operating_revenue": 48496.0,
        "other_income": 1450.0,
        "total_revenue": 49946.0,
        "interest_income": 460.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 460.0,
        "filing_date": "2024-05-22",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 18 - Non-Current & Current Borrowings",
        "cash_note_ref": "Note 11 - Cash and Bank Balances",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 26 - Other Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "CIPLA.NS",
        "symbol": "CIPLA",
        "isin": "INE059A01026",
        "bse_code": "500087",
        "company_name": "Cipla Limited",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals & Respiratory Care",
        "business_summary": "Global healthcare company with therapeutic focus on respiratory, anti-retroviral, urology, and cardiology formulations.",
        "current_price": 1580.0,
        "market_cap": 127500.0,
        "avg_36m_market_cap": 98400.0,
        "shares_outstanding": 807000000,
        "pe_ratio": 30.8,
        "pb_ratio": 4.5,
        "dividend_yield": 0.009,
        "last_dividend_per_share": 13.0,
        "total_assets": 34800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 420.0,
        "lease_liabilities": 910.0,
        "total_debt": 1330.0,
        "cash_and_bank": 3200.0,
        "current_investments": 4800.0,
        "total_cash_and_investments": 8000.0,
        "total_receivables": 5100.0,
        "total_inventories": 5800.0,
        "current_liabilities": 6200.0,
        "operating_revenue": 25774.0,
        "other_income": 680.0,
        "total_revenue": 26454.0,
        "interest_income": 220.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 220.0,
        "filing_date": "2024-05-10",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 16 - Borrowings",
        "cash_note_ref": "Note 9 - Cash & Cash Equivalents",
        "rec_note_ref": "Note 8 - Trade Receivables",
        "income_note_ref": "Note 24 - Other Non-Operating Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "DRREDDY.NS",
        "symbol": "DRREDDY",
        "isin": "INE089A01023",
        "bse_code": "500124",
        "company_name": "Dr. Reddy's Laboratories Limited",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals & Active Ingredients",
        "business_summary": "Integrated pharmaceutical firm offering generics, APIs, biosimilars, and proprietary healthcare products.",
        "current_price": 6650.0,
        "market_cap": 110900.0,
        "avg_36m_market_cap": 91200.0,
        "shares_outstanding": 166800000,
        "pe_ratio": 20.1,
        "pb_ratio": 3.7,
        "dividend_yield": 0.006,
        "last_dividend_per_share": 40.0,
        "total_assets": 39400.0,
        "long_term_debt": 680.0,
        "short_term_debt": 2150.0,
        "lease_liabilities": 880.0,
        "total_debt": 3710.0,
        "cash_and_bank": 3400.0,
        "current_investments": 4100.0,
        "total_cash_and_investments": 7500.0,
        "total_receivables": 6800.0,
        "total_inventories": 6200.0,
        "current_liabilities": 9100.0,
        "operating_revenue": 27916.0,
        "other_income": 950.0,
        "total_revenue": 28866.0,
        "interest_income": 300.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 300.0,
        "filing_date": "2024-05-07",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 17 - Borrowings Schedule",
        "cash_note_ref": "Note 11 - Cash and Cash Equivalents",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 25 - Other Income Details",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "DIVISLAB.NS",
        "symbol": "DIVISLAB",
        "isin": "INE361B01024",
        "bse_code": "532488",
        "company_name": "Divi's Laboratories Limited",
        "sector": "Healthcare",
        "industry": "Active Pharmaceutical Ingredients (APIs)",
        "business_summary": "World-leading producer of generic APIs, nutraceutical ingredients, and custom pharmaceutical synthesis.",
        "current_price": 5420.0,
        "market_cap": 143900.0,
        "avg_36m_market_cap": 112000.0,
        "shares_outstanding": 265400000,
        "pe_ratio": 72.5,
        "pb_ratio": 10.4,
        "dividend_yield": 0.006,
        "last_dividend_per_share": 30.0,
        "total_assets": 15800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 0.0,
        "total_debt": 0.0,
        "cash_and_bank": 1400.0,
        "current_investments": 2850.0,
        "total_cash_and_investments": 4250.0,
        "total_receivables": 2100.0,
        "total_inventories": 3400.0,
        "current_liabilities": 1820.0,
        "operating_revenue": 7845.0,
        "other_income": 320.0,
        "total_revenue": 8165.0,
        "interest_income": 110.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 110.0,
        "filing_date": "2024-05-25",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Zero Debt Balance Sheet Disclosure",
        "cash_note_ref": "Note 7 - Bank Balances & Mutual Funds",
        "rec_note_ref": "Note 6 - Trade Receivables",
        "income_note_ref": "Note 19 - Interest from Banks",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 3. SHARIAH COMPLIANT - CONSUMER & CHEMICALS
    # -------------------------------------------------------------
    {
        "ticker": "HINDUNILVR.NS",
        "symbol": "HINDUNILVR",
        "isin": "INE030A01027",
        "bse_code": "500696",
        "company_name": "Hindustan Unilever Limited",
        "sector": "Fast Moving Consumer Goods",
        "industry": "Personal Care & Packaged Foods",
        "business_summary": "India's largest FMCG corporation offering soaps, detergents, oral care, tea, and packaged nutritional foods.",
        "current_price": 2740.0,
        "market_cap": 643800.0,
        "avg_36m_market_cap": 592000.0,
        "shares_outstanding": 2349000000,
        "pe_ratio": 62.4,
        "pb_ratio": 12.8,
        "dividend_yield": 0.016,
        "last_dividend_per_share": 42.0,
        "total_assets": 75800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 2400.0,
        "total_debt": 2400.0,
        "cash_and_bank": 3400.0,
        "current_investments": 4800.0,
        "total_cash_and_investments": 8200.0,
        "total_receivables": 3200.0,
        "total_inventories": 4800.0,
        "current_liabilities": 14200.0,
        "operating_revenue": 61896.0,
        "other_income": 1240.0,
        "total_revenue": 63136.0,
        "interest_income": 610.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 610.0,
        "filing_date": "2024-04-24",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Ind AS 116 Lease Obligations",
        "cash_note_ref": "Note 11 - Cash and Bank Balances",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 27 - Other Income (Interest on Bank Deposits)",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "TITAN.NS",
        "symbol": "TITAN",
        "isin": "INE280A01028",
        "bse_code": "500114",
        "company_name": "Titan Company Limited",
        "sector": "Consumer Discretionary",
        "industry": "Jewellery, Watches & Eyewear",
        "business_summary": "Tata Group luxury and lifestyle leader managing Tanishq, Fastrack, Titan Watches, and Mia.",
        "current_price": 3480.0,
        "market_cap": 308900.0,
        "avg_36m_market_cap": 254000.0,
        "shares_outstanding": 887800000,
        "pe_ratio": 88.5,
        "pb_ratio": 24.2,
        "dividend_yield": 0.003,
        "last_dividend_per_share": 11.0,
        "total_assets": 28400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 2450.0,
        "lease_liabilities": 2840.0,
        "total_debt": 5290.0,
        "cash_and_bank": 1420.0,
        "current_investments": 1850.0,
        "total_cash_and_investments": 3270.0,
        "total_receivables": 980.0,
        "total_inventories": 18200.0,
        "current_liabilities": 11400.0,
        "operating_revenue": 51084.0,
        "other_income": 610.0,
        "total_revenue": 51694.0,
        "interest_income": 190.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 190.0,
        "filing_date": "2024-05-03",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 17 - Borrowings & Lease Liabilities",
        "cash_note_ref": "Note 9 - Cash & Bank",
        "rec_note_ref": "Note 8 - Trade Receivables",
        "income_note_ref": "Note 22 - Finance Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "ASIANPAINT.NS",
        "symbol": "ASIANPAINT",
        "isin": "INE021A01026",
        "bse_code": "500820",
        "company_name": "Asian Paints Limited",
        "sector": "Materials",
        "industry": "Paints, Coatings & Home Decor",
        "business_summary": "India's premier paint and coating manufacturer with extensive decorative, industrial, and waterproof solutions.",
        "current_price": 3120.0,
        "market_cap": 299200.0,
        "avg_36m_market_cap": 284500.0,
        "shares_outstanding": 959200000,
        "pe_ratio": 54.1,
        "pb_ratio": 15.6,
        "dividend_yield": 0.011,
        "last_dividend_per_share": 33.25,
        "total_assets": 28900.0,
        "long_term_debt": 0.0,
        "short_term_debt": 1420.0,
        "lease_liabilities": 1120.0,
        "total_debt": 2540.0,
        "cash_and_bank": 1820.0,
        "current_investments": 3200.0,
        "total_cash_and_investments": 5020.0,
        "total_receivables": 4120.0,
        "total_inventories": 5840.0,
        "current_liabilities": 8200.0,
        "operating_revenue": 35494.0,
        "other_income": 720.0,
        "total_revenue": 36214.0,
        "interest_income": 240.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 240.0,
        "filing_date": "2024-05-09",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 16 - Borrowings & Ind AS 116",
        "cash_note_ref": "Note 10 - Cash & Bank Balances",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 24 - Interest and Other Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "PIDILITIND.NS",
        "symbol": "PIDILITIND",
        "isin": "INE318A01026",
        "bse_code": "500331",
        "company_name": "Pidilite Industries Limited",
        "sector": "Materials",
        "industry": "Adhesives, Sealants & Construction Chemicals",
        "business_summary": "Manufacturer of world-renowned consumer adhesive Fevicol, waterproofing brand Dr. Fixit, and synthetic resins.",
        "current_price": 3190.0,
        "market_cap": 162200.0,
        "avg_36m_market_cap": 128400.0,
        "shares_outstanding": 508500000,
        "pe_ratio": 78.4,
        "pb_ratio": 17.5,
        "dividend_yield": 0.005,
        "last_dividend_per_share": 16.0,
        "total_assets": 13900.0,
        "long_term_debt": 0.0,
        "short_term_debt": 180.0,
        "lease_liabilities": 490.0,
        "total_debt": 670.0,
        "cash_and_bank": 920.0,
        "current_investments": 1450.0,
        "total_cash_and_investments": 2370.0,
        "total_receivables": 1940.0,
        "total_inventories": 2100.0,
        "current_liabilities": 3100.0,
        "operating_revenue": 12385.0,
        "other_income": 190.0,
        "total_revenue": 12575.0,
        "interest_income": 65.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 65.0,
        "filing_date": "2024-05-08",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 15 - Borrowings",
        "cash_note_ref": "Note 8 - Liquid Financial Assets",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Note 21 - Other Non-Operating Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "DABUR.NS",
        "symbol": "DABUR",
        "isin": "INE016A01026",
        "bse_code": "500096",
        "company_name": "Dabur India Limited",
        "sector": "Fast Moving Consumer Goods",
        "industry": "Ayurvedic Personal Care & Consumer Health",
        "business_summary": "Global herbal and ayurvedic health care, personal care, and organic juice beverage brand.",
        "current_price": 630.0,
        "market_cap": 111600.0,
        "avg_36m_market_cap": 98700.0,
        "shares_outstanding": 1772000000,
        "pe_ratio": 54.8,
        "pb_ratio": 10.2,
        "dividend_yield": 0.012,
        "last_dividend_per_share": 8.0,
        "total_assets": 14200.0,
        "long_term_debt": 450.0,
        "short_term_debt": 720.0,
        "lease_liabilities": 280.0,
        "total_debt": 1450.0,
        "cash_and_bank": 1120.0,
        "current_investments": 2840.0,
        "total_cash_and_investments": 3960.0,
        "total_receivables": 1420.0,
        "total_inventories": 2450.0,
        "current_liabilities": 3650.0,
        "operating_revenue": 12404.0,
        "other_income": 490.0,
        "total_revenue": 12894.0,
        "interest_income": 145.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 145.0,
        "filing_date": "2024-05-02",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 18 - Borrowings",
        "cash_note_ref": "Note 10 - Cash & Bank",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 25 - Finance & Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "MARICO.NS",
        "symbol": "MARICO",
        "isin": "INE196A01026",
        "bse_code": "531642",
        "company_name": "Marico Limited",
        "sector": "Fast Moving Consumer Goods",
        "industry": "Edible Oils & Hair Care",
        "business_summary": "Consumer products leader holding iconic brands Parachute, Saffola, Livon, and Beardo.",
        "current_price": 645.0,
        "market_cap": 83400.0,
        "avg_36m_market_cap": 68400.0,
        "shares_outstanding": 1293000000,
        "pe_ratio": 52.8,
        "pb_ratio": 18.2,
        "dividend_yield": 0.015,
        "last_dividend_per_share": 9.5,
        "total_assets": 6840.0,
        "long_term_debt": 0.0,
        "short_term_debt": 410.0,
        "lease_liabilities": 260.0,
        "total_debt": 670.0,
        "cash_and_bank": 840.0,
        "current_investments": 950.0,
        "total_cash_and_investments": 1790.0,
        "total_receivables": 920.0,
        "total_inventories": 1640.0,
        "current_liabilities": 2420.0,
        "operating_revenue": 9653.0,
        "other_income": 180.0,
        "total_revenue": 9833.0,
        "interest_income": 72.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 72.0,
        "filing_date": "2024-05-06",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Borrowings",
        "cash_note_ref": "Note 8 - Cash and Bank Balances",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Note 21 - Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "DEEPAKNTR.NS",
        "symbol": "DEEPAKNTR",
        "isin": "INE288B01029",
        "bse_code": "506401",
        "company_name": "Deepak Nitrite Limited",
        "sector": "Materials",
        "industry": "Specialty Chemicals & Intermediates",
        "business_summary": "Chemical intermediate manufacturing corporation producing basic chemicals, fine chemicals, and phenolics.",
        "current_price": 2850.0,
        "market_cap": 38870.0,
        "avg_36m_market_cap": 31200.0,
        "shares_outstanding": 136400000,
        "pe_ratio": 46.2,
        "pb_ratio": 8.1,
        "dividend_yield": 0.003,
        "last_dividend_per_share": 8.5,
        "total_assets": 6420.0,
        "long_term_debt": 0.0,
        "short_term_debt": 60.0,
        "lease_liabilities": 85.0,
        "total_debt": 145.0,
        "cash_and_bank": 320.0,
        "current_investments": 490.0,
        "total_cash_and_investments": 810.0,
        "total_receivables": 940.0,
        "total_inventories": 680.0,
        "current_liabilities": 1120.0,
        "operating_revenue": 7682.0,
        "other_income": 95.0,
        "total_revenue": 7777.0,
        "interest_income": 35.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 35.0,
        "filing_date": "2024-05-14",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 15 - Borrowings",
        "cash_note_ref": "Note 9 - Cash & Bank",
        "rec_note_ref": "Note 8 - Trade Receivables",
        "income_note_ref": "Note 20 - Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 4. SHARIAH COMPLIANT - CAPITAL GOODS, POWER & INFRASTRUCTURE
    # -------------------------------------------------------------
    {
        "ticker": "SIEMENS.NS",
        "symbol": "SIEMENS",
        "isin": "INE003A01024",
        "bse_code": "500550",
        "company_name": "Siemens Limited",
        "sector": "Industrials",
        "industry": "Electrical Equipment & Automation",
        "business_summary": "Pioneer in energy transmission, smart infrastructure, industrial automation, and modern rail mobility.",
        "current_price": 7240.0,
        "market_cap": 257800.0,
        "avg_36m_market_cap": 164000.0,
        "shares_outstanding": 356100000,
        "pe_ratio": 98.2,
        "pb_ratio": 17.5,
        "dividend_yield": 0.002,
        "last_dividend_per_share": 10.0,
        "total_assets": 21800.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 0.0,
        "total_debt": 0.0,
        "cash_and_bank": 3400.0,
        "current_investments": 2800.0,
        "total_cash_and_investments": 6200.0,
        "total_receivables": 4900.0,
        "total_inventories": 2800.0,
        "current_liabilities": 7800.0,
        "operating_revenue": 19612.0,
        "other_income": 410.0,
        "total_revenue": 20022.0,
        "interest_income": 220.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 220.0,
        "filing_date": "2024-05-15",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Zero Debt Balance Sheet Disclosure",
        "cash_note_ref": "Note 11 - Bank Deposits & Mutual Funds",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 24 - Interest from Banks",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "ABB.NS",
        "symbol": "ABB",
        "isin": "INE117A01022",
        "bse_code": "500002",
        "company_name": "ABB India Limited",
        "sector": "Industrials",
        "industry": "Heavy Electrical Equipment & Robotics",
        "business_summary": "Global engineering giant specializing in robotics, process automation, motion drives, and smart electrification.",
        "current_price": 8150.0,
        "market_cap": 172700.0,
        "avg_36m_market_cap": 118000.0,
        "shares_outstanding": 211900000,
        "pe_ratio": 105.4,
        "pb_ratio": 26.8,
        "dividend_yield": 0.003,
        "last_dividend_per_share": 23.8,
        "total_assets": 11400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 0.0,
        "total_debt": 0.0,
        "cash_and_bank": 2900.0,
        "current_investments": 1400.0,
        "total_cash_and_investments": 4300.0,
        "total_receivables": 2600.0,
        "total_inventories": 1700.0,
        "current_liabilities": 4900.0,
        "operating_revenue": 10447.0,
        "other_income": 210.0,
        "total_revenue": 10657.0,
        "interest_income": 120.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 120.0,
        "filing_date": "2024-05-11",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Zero Debt Balance Sheet Disclosure",
        "cash_note_ref": "Note 10 - Cash & Bank Balances",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 21 - Other Income (Interest on Deposits)",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "THERMAX.NS",
        "symbol": "THERMAX",
        "isin": "INE152A01029",
        "bse_code": "500411",
        "company_name": "Thermax Limited",
        "sector": "Industrials",
        "industry": "Clean Energy & Environmental Solutions",
        "business_summary": "Energy and environment solutions provider enabling decarbonization, green hydrogen, and industrial water treatment.",
        "current_price": 5120.0,
        "market_cap": 60900.0,
        "avg_36m_market_cap": 38400.0,
        "shares_outstanding": 119000000,
        "pe_ratio": 78.9,
        "pb_ratio": 12.4,
        "dividend_yield": 0.002,
        "last_dividend_per_share": 12.0,
        "total_assets": 8900.0,
        "long_term_debt": 0.0,
        "short_term_debt": 320.0,
        "lease_liabilities": 140.0,
        "total_debt": 460.0,
        "cash_and_bank": 1150.0,
        "current_investments": 1420.0,
        "total_cash_and_investments": 2570.0,
        "total_receivables": 2150.0,
        "total_inventories": 980.0,
        "current_liabilities": 4100.0,
        "operating_revenue": 9325.0,
        "other_income": 190.0,
        "total_revenue": 9515.0,
        "interest_income": 85.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 85.0,
        "filing_date": "2024-05-17",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Borrowings",
        "cash_note_ref": "Note 9 - Cash & Bank",
        "rec_note_ref": "Note 8 - Trade Receivables",
        "income_note_ref": "Note 22 - Finance Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "POLYCAB.NS",
        "symbol": "POLYCAB",
        "isin": "INE455K01017",
        "bse_code": "542652",
        "company_name": "Polycab India Limited",
        "sector": "Industrials",
        "industry": "Wires, Cables & Fast Moving Electrical Goods",
        "business_summary": "India's largest manufacturer of power cables, copper wire rods, and fast-moving electrical appliances.",
        "current_price": 6840.0,
        "market_cap": 102800.0,
        "avg_36m_market_cap": 68200.0,
        "shares_outstanding": 150300000,
        "pe_ratio": 54.2,
        "pb_ratio": 12.8,
        "dividend_yield": 0.004,
        "last_dividend_per_share": 30.0,
        "total_assets": 11900.0,
        "long_term_debt": 0.0,
        "short_term_debt": 110.0,
        "lease_liabilities": 140.0,
        "total_debt": 250.0,
        "cash_and_bank": 1100.0,
        "current_investments": 1480.0,
        "total_cash_and_investments": 2580.0,
        "total_receivables": 1940.0,
        "total_inventories": 3400.0,
        "current_liabilities": 3100.0,
        "operating_revenue": 18039.0,
        "other_income": 240.0,
        "total_revenue": 18279.0,
        "interest_income": 95.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 95.0,
        "filing_date": "2024-05-10",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 16 - Borrowings",
        "cash_note_ref": "Note 10 - Cash & Bank",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 23 - Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "BHARTIARTL.NS",
        "symbol": "BHARTIARTL",
        "isin": "INE397D01024",
        "bse_code": "532454",
        "company_name": "Bharti Airtel Limited",
        "sector": "Telecommunication",
        "industry": "Wireless & Digital Communications",
        "business_summary": "Leading global telecommunications company with operations across India, South Asia, and 14 African nations.",
        "current_price": 1650.0,
        "market_cap": 985000.0,
        "avg_36m_market_cap": 745000.0,
        "shares_outstanding": 5969000000,
        "pe_ratio": 74.2,
        "pb_ratio": 10.8,
        "dividend_yield": 0.005,
        "last_dividend_per_share": 8.0,
        "total_assets": 448000.0,
        "long_term_debt": 115000.0,
        "short_term_debt": 28000.0,
        "lease_liabilities": 58000.0,
        "total_debt": 201000.0,
        "cash_and_bank": 18500.0,
        "current_investments": 12400.0,
        "total_cash_and_investments": 30900.0,
        "total_receivables": 6200.0,
        "total_inventories": 280.0,
        "current_liabilities": 94000.0,
        "operating_revenue": 149982.0,
        "other_income": 1420.0,
        "total_revenue": 151402.0,
        "interest_income": 980.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 980.0,
        "filing_date": "2024-05-14",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 20 - Borrowings and Spectrum Liabilities",
        "cash_note_ref": "Note 12 - Cash & Cash Equivalents",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Note 28 - Finance Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "TATAMOTORS.NS",
        "symbol": "TATAMOTORS",
        "isin": "INE155A01022",
        "bse_code": "500570",
        "company_name": "Tata Motors Limited",
        "sector": "Automobile",
        "industry": "Commercial Vehicles, Passenger Cars & EVs",
        "business_summary": "Automotive titan manufacturing commercial trucks, electric passenger cars, and British luxury icons Jaguar Land Rover.",
        "current_price": 980.0,
        "market_cap": 360500.0,
        "avg_36m_market_cap": 254000.0,
        "shares_outstanding": 3678000000,
        "pe_ratio": 11.2,
        "pb_ratio": 3.8,
        "dividend_yield": 0.006,
        "last_dividend_per_share": 6.0,
        "total_assets": 354000.0,
        "long_term_debt": 38400.0,
        "short_term_debt": 14200.0,
        "lease_liabilities": 7800.0,
        "total_debt": 60400.0,
        "cash_and_bank": 34800.0,
        "current_investments": 19400.0,
        "total_cash_and_investments": 54200.0,
        "total_receivables": 16400.0,
        "total_inventories": 44800.0,
        "current_liabilities": 142000.0,
        "operating_revenue": 437928.0,
        "other_income": 4120.0,
        "total_revenue": 442048.0,
        "interest_income": 2840.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 2840.0,
        "filing_date": "2024-05-10",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 21 - Borrowings",
        "cash_note_ref": "Note 14 - Cash & Cash Equivalents",
        "rec_note_ref": "Note 13 - Trade Receivables",
        "income_note_ref": "Note 30 - Other Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "ULTRACEMCO.NS",
        "symbol": "ULTRACEMCO",
        "isin": "INE481G01011",
        "bse_code": "532538",
        "company_name": "UltraTech Cement Limited",
        "sector": "Materials",
        "industry": "Cement & Building Materials",
        "business_summary": "India's largest cement manufacturing company with global presence and extensive ready-mix concrete network.",
        "current_price": 11450.0,
        "market_cap": 330600.0,
        "avg_36m_market_cap": 258000.0,
        "shares_outstanding": 288700000,
        "pe_ratio": 47.1,
        "pb_ratio": 5.4,
        "dividend_yield": 0.006,
        "last_dividend_per_share": 70.0,
        "total_assets": 104500.0,
        "long_term_debt": 8400.0,
        "short_term_debt": 3200.0,
        "lease_liabilities": 2100.0,
        "total_debt": 13700.0,
        "cash_and_bank": 2100.0,
        "current_investments": 7400.0,
        "total_cash_and_investments": 9500.0,
        "total_receivables": 4100.0,
        "total_inventories": 7800.0,
        "current_liabilities": 21400.0,
        "operating_revenue": 70908.0,
        "other_income": 1120.0,
        "total_revenue": 72028.0,
        "interest_income": 410.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 410.0,
        "filing_date": "2024-04-29",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Borrowings",
        "cash_note_ref": "Note 12 - Cash & Current Investments",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Note 26 - Other Income",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 5. DIVERGENT & BORDERLINE EQUITIES (Key for testing dual-standard)
    # -------------------------------------------------------------
    {
        # Passes AAOIFI (Cash/Mcap = 11.3%), FAILS TASIS (Cash/Assets = 41.5% > 33%)
        "ticker": "OFSS.NS",
        "symbol": "OFSS",
        "isin": "INE881D01027",
        "bse_code": "532466",
        "company_name": "Oracle Financial Services Software Limited",
        "sector": "Information Technology",
        "industry": "Banking Software Products",
        "business_summary": "World-class financial software and core-banking technology suites (software vendor, not a bank).",
        "current_price": 10800.0,
        "market_cap": 93500.0,
        "avg_36m_market_cap": 48200.0,
        "shares_outstanding": 86600000,
        "pe_ratio": 42.1,
        "pb_ratio": 11.2,
        "dividend_yield": 0.022,
        "last_dividend_per_share": 240.0,
        "total_assets": 13200.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 210.0,
        "total_debt": 210.0,
        "cash_and_bank": 3200.0,
        "current_investments": 2280.0,
        "total_cash_and_investments": 5480.0,  # 5480 / 13200 = 41.5% (> 33% TASIS failure!)
        "total_receivables": 1420.0,
        "total_inventories": 0.0,
        "current_liabilities": 2150.0,
        "operating_revenue": 6373.0,
        "other_income": 280.0,
        "total_revenue": 6653.0,
        "interest_income": 190.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 190.0,
        "filing_date": "2024-05-08",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Leases",
        "cash_note_ref": "Note 8 - Cash, Bank & Liquid Mutual Funds",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Note 18 - Deposit Interest",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        # Passes TASIS (Debt/Assets = 26.8% < 33%), FAILS AAOIFI (Debt/Mcap = 41.2% > 33%)
        "ticker": "JINDALSTEL.NS",
        "symbol": "JINDALSTEL",
        "isin": "INE749A01030",
        "bse_code": "532286",
        "company_name": "Jindal Steel & Power Limited",
        "sector": "Materials",
        "industry": "Steel Manufacturing & Infrastructure",
        "business_summary": "Leading industrial conglomerate manufacturing structural steel, rails, and heavy plates with extensive physical capital.",
        "current_price": 960.0,
        "market_cap": 97900.0,
        "avg_36m_market_cap": 62400.0,
        "shares_outstanding": 1020000000,
        "pe_ratio": 16.5,
        "pb_ratio": 2.2,
        "dividend_yield": 0.002,
        "last_dividend_per_share": 2.0,
        "total_assets": 95800.0,
        "long_term_debt": 18400.0,
        "short_term_debt": 4800.0,
        "lease_liabilities": 2500.0,
        "total_debt": 25700.0,  # 25700 / 95800 = 26.8% (Passes TASIS); 25700 / 62400 = 41.2% (Fails AAOIFI!)
        "cash_and_bank": 3800.0,
        "current_investments": 2400.0,
        "total_cash_and_investments": 6200.0,
        "total_receivables": 3200.0,
        "total_inventories": 14200.0,
        "current_liabilities": 22400.0,
        "operating_revenue": 50840.0,
        "other_income": 380.0,
        "total_revenue": 51220.0,
        "interest_income": 180.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 180.0,
        "filing_date": "2024-05-18",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 20 - Long-Term & Short-Term Borrowings",
        "cash_note_ref": "Note 12 - Cash & Bank",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Note 27 - Other Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        # QUESTIONABLE / MUSHBOOH STATUS: Debt ratio in warning zone (32.4% on AAOIFI, 32.1% on TASIS)
        "ticker": "TATAPOWER.NS",
        "symbol": "TATAPOWER",
        "isin": "INE245A01021",
        "bse_code": "500400",
        "company_name": "Tata Power Company Limited",
        "sector": "Utilities",
        "industry": "Electric Utilities & Clean Renewable Power",
        "business_summary": "Pioneering integrated power company transitioning heavily to solar, wind, and transmission corridors.",
        "current_price": 420.0,
        "market_cap": 134200.0,
        "avg_36m_market_cap": 118400.0,
        "shares_outstanding": 3195000000,
        "pe_ratio": 34.2,
        "pb_ratio": 4.1,
        "dividend_yield": 0.005,
        "last_dividend_per_share": 2.0,
        "total_assets": 119500.0,
        "long_term_debt": 28400.0,
        "short_term_debt": 6800.0,
        "lease_liabilities": 3200.0,
        "total_debt": 38400.0,  # 38400 / 118400 = 32.43% (Warning zone [32.0% - 33.0%])
        "cash_and_bank": 5100.0,
        "current_investments": 3400.0,
        "total_cash_and_investments": 8500.0,
        "total_receivables": 9400.0,
        "total_inventories": 3800.0,
        "current_liabilities": 34000.0,
        "operating_revenue": 61449.0,
        "other_income": 980.0,
        "total_revenue": 62429.0,
        "interest_income": 620.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 620.0,
        "filing_date": "2024-05-08",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 22 - Borrowings Schedule",
        "cash_note_ref": "Note 14 - Cash & Bank",
        "rec_note_ref": "Note 13 - Trade Receivables",
        "income_note_ref": "Note 31 - Other Non-Operating Income",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        # QUESTIONABLE ON IMPERMISSIBLE INCOME: Incidental interest income is 4.75% (Warning zone [4.5% - 5.0%])
        "ticker": "APOLLOTYRE.NS",
        "symbol": "APOLLOTYRE",
        "isin": "INE438A01022",
        "bse_code": "500877",
        "company_name": "Apollo Tyres Limited",
        "sector": "Automobile",
        "industry": "Tyres & Rubber Products",
        "business_summary": "Leading tyre manufacturing corporation catering to commercial, passenger, and agricultural vehicles.",
        "current_price": 520.0,
        "market_cap": 33020.0,
        "avg_36m_market_cap": 27800.0,
        "shares_outstanding": 635100000,
        "pe_ratio": 19.5,
        "pb_ratio": 2.4,
        "dividend_yield": 0.009,
        "last_dividend_per_share": 4.5,
        "total_assets": 27400.0,
        "long_term_debt": 3400.0,
        "short_term_debt": 1200.0,
        "lease_liabilities": 750.0,
        "total_debt": 5350.0,  # 5350 / 27800 = 19.2% (Debt compliant)
        "cash_and_bank": 1120.0,
        "current_investments": 940.0,
        "total_cash_and_investments": 2060.0,
        "total_receivables": 2400.0,
        "total_inventories": 4100.0,
        "current_liabilities": 7800.0,
        "operating_revenue": 25378.0,
        "other_income": 1280.0,
        "total_revenue": 26658.0,
        "interest_income": 1265.0,  # 1265 / 26658 = 4.745% (In warning zone [4.5% - 5.0%])
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 1265.0,
        "filing_date": "2024-05-14",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Borrowings",
        "cash_note_ref": "Note 12 - Cash & Bank",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Note 27 - Treasury Income & Deposit Interest",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 6. NON-COMPLIANT - BANKING & CONVENTIONAL FINANCE (RIBA)
    # -------------------------------------------------------------
    {
        "ticker": "HDFCBANK.NS",
        "symbol": "HDFCBANK",
        "isin": "INE040A01034",
        "bse_code": "500180",
        "company_name": "HDFC Bank Limited",
        "sector": "Financial Services",
        "industry": "Commercial Banking",
        "business_summary": "India's largest private commercial bank engaged in retail and corporate lending with interest-bearing debt intermediation.",
        "current_price": 1640.0,
        "market_cap": 1245000.0,
        "avg_36m_market_cap": 980000.0,
        "shares_outstanding": 7590000000,
        "pe_ratio": 19.8,
        "pb_ratio": 2.8,
        "dividend_yield": 0.012,
        "last_dividend_per_share": 19.5,
        "total_assets": 3617000.0,
        "long_term_debt": 714000.0,
        "short_term_debt": 142000.0,
        "lease_liabilities": 8400.0,
        "total_debt": 864400.0,
        "cash_and_bank": 248000.0,
        "current_investments": 745000.0,
        "total_cash_and_investments": 993000.0,
        "total_receivables": 2510000.0,
        "total_inventories": 0.0,
        "current_liabilities": 3120000.0,
        "operating_revenue": 285400.0,
        "other_income": 42000.0,
        "total_revenue": 327400.0,
        "interest_income": 268000.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 268000.0,
        "filing_date": "2024-04-20",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Borrowings Schedule (RBI Banking Format)",
        "cash_note_ref": "Cash & Balances with RBI",
        "rec_note_ref": "Advances (Interest-Bearing Loan Book)",
        "income_note_ref": "Interest Earned on Advances & Investments",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "ICICIBANK.NS",
        "symbol": "ICICIBANK",
        "isin": "INE090A01021",
        "bse_code": "532174",
        "company_name": "ICICI Bank Limited",
        "sector": "Financial Services",
        "industry": "Commercial Banking",
        "business_summary": "Major private commercial bank providing interest-based loans, corporate finance, and treasury services.",
        "current_price": 1280.0,
        "market_cap": 898000.0,
        "avg_36m_market_cap": 642000.0,
        "shares_outstanding": 7015000000,
        "pe_ratio": 18.2,
        "pb_ratio": 3.1,
        "dividend_yield": 0.008,
        "last_dividend_per_share": 10.0,
        "total_assets": 2364000.0,
        "long_term_debt": 412000.0,
        "short_term_debt": 98000.0,
        "lease_liabilities": 5400.0,
        "total_debt": 515400.0,
        "cash_and_bank": 184000.0,
        "current_investments": 540000.0,
        "total_cash_and_investments": 724000.0,
        "total_receivables": 1620000.0,
        "total_inventories": 0.0,
        "current_liabilities": 2040000.0,
        "operating_revenue": 182400.0,
        "other_income": 26800.0,
        "total_revenue": 209200.0,
        "interest_income": 172000.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 172000.0,
        "filing_date": "2024-04-27",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Borrowings Schedule",
        "cash_note_ref": "Balances with RBI",
        "rec_note_ref": "Advances (Loan Assets)",
        "income_note_ref": "Interest Income on Loans",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "SBIN.NS",
        "symbol": "SBIN",
        "isin": "INE062A01020",
        "bse_code": "500112",
        "company_name": "State Bank of India",
        "sector": "Financial Services",
        "industry": "Public Sector Commercial Banking",
        "business_summary": "India's largest public sector financial conglomerate dealing in retail deposits and interest-bearing credit creation.",
        "current_price": 790.0,
        "market_cap": 705000.0,
        "avg_36m_market_cap": 528000.0,
        "shares_outstanding": 8924000000,
        "pe_ratio": 10.4,
        "pb_ratio": 1.7,
        "dividend_yield": 0.017,
        "last_dividend_per_share": 13.7,
        "total_assets": 6184000.0,
        "long_term_debt": 842000.0,
        "short_term_debt": 310000.0,
        "lease_liabilities": 11200.0,
        "total_debt": 1163200.0,
        "cash_and_bank": 348000.0,
        "current_investments": 1780000.0,
        "total_cash_and_investments": 2128000.0,
        "total_receivables": 3720000.0,
        "total_inventories": 0.0,
        "current_liabilities": 5420000.0,
        "operating_revenue": 432800.0,
        "other_income": 58400.0,
        "total_revenue": 491200.0,
        "interest_income": 412000.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 412000.0,
        "filing_date": "2024-05-09",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Borrowings (Schedule 4)",
        "cash_note_ref": "Cash & Balances (Schedule 6)",
        "rec_note_ref": "Advances (Schedule 9)",
        "income_note_ref": "Interest Earned (Schedule 13)",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "AXISBANK.NS",
        "symbol": "AXISBANK",
        "isin": "INE238A01034",
        "bse_code": "532215",
        "company_name": "Axis Bank Limited",
        "sector": "Financial Services",
        "industry": "Commercial Banking",
        "business_summary": "Full-service private sector commercial bank offering retail credit, mortgages, and corporate working capital finance.",
        "current_price": 1180.0,
        "market_cap": 364500.0,
        "avg_36m_market_cap": 284000.0,
        "shares_outstanding": 3089000000,
        "pe_ratio": 14.1,
        "pb_ratio": 2.2,
        "dividend_yield": 0.001,
        "last_dividend_per_share": 1.0,
        "total_assets": 1478000.0,
        "long_term_debt": 242000.0,
        "short_term_debt": 68000.0,
        "lease_liabilities": 4100.0,
        "total_debt": 314100.0,
        "cash_and_bank": 112000.0,
        "current_investments": 348000.0,
        "total_cash_and_investments": 460000.0,
        "total_receivables": 984000.0,
        "total_inventories": 0.0,
        "current_liabilities": 1280000.0,
        "operating_revenue": 118400.0,
        "other_income": 19400.0,
        "total_revenue": 137800.0,
        "interest_income": 109200.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 109200.0,
        "filing_date": "2024-04-24",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Borrowings (Schedule 4)",
        "cash_note_ref": "Cash & Bank (Schedule 6)",
        "rec_note_ref": "Advances (Schedule 9)",
        "income_note_ref": "Interest Earned (Schedule 13)",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },
    {
        "ticker": "BAJFINANCE.NS",
        "symbol": "BAJFINANCE",
        "isin": "INE296A01024",
        "bse_code": "500034",
        "company_name": "Bajaj Finance Limited",
        "sector": "Financial Services",
        "industry": "Non-Banking Financial Company (NBFC - Consumer Lending)",
        "business_summary": "High-growth consumer finance company issuing unsecured consumer durable loans, personal loans, and EMI financing.",
        "current_price": 7150.0,
        "market_cap": 441800.0,
        "avg_36m_market_cap": 412000.0,
        "shares_outstanding": 618000000,
        "pe_ratio": 30.4,
        "pb_ratio": 5.8,
        "dividend_yield": 0.005,
        "last_dividend_per_share": 36.0,
        "total_assets": 371000.0,
        "long_term_debt": 248000.0,
        "short_term_debt": 54000.0,
        "lease_liabilities": 2400.0,
        "total_debt": 304400.0,
        "cash_and_bank": 9800.0,
        "current_investments": 28400.0,
        "total_cash_and_investments": 38200.0,
        "total_receivables": 328000.0,
        "total_inventories": 0.0,
        "current_liabilities": 284000.0,
        "operating_revenue": 54980.0,
        "other_income": 320.0,
        "total_revenue": 55300.0,
        "interest_income": 51200.0,
        "prohibited_secondary_revenue": 0.0,
        "total_impermissible_income": 51200.0,
        "filing_date": "2024-04-25",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Debt Securities & Borrowings",
        "cash_note_ref": "Note 10 - Cash & Bank Balances",
        "rec_note_ref": "Note 8 - Loans & Financing Receivables",
        "income_note_ref": "Note 24 - Interest Income on Consumer Credit",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 7. NON-COMPLIANT - ALCOHOL & INTOXICANTS (KHAMR)
    # -------------------------------------------------------------
    {
        "ticker": "UNITDSPR.NS",
        "symbol": "UNITDSPR",
        "isin": "INE854D01024",
        "bse_code": "532432",
        "company_name": "United Spirits Limited (Diageo India)",
        "sector": "Consumer Staples",
        "industry": "Distilleries, Breweries & Alcohol",
        "business_summary": "Manufacture and marketing of commercial alcoholic spirits (whisky, rum, vodka, gin) including McDowell's, Royal Challenge, and Black Dog.",
        "current_price": 1390.0,
        "market_cap": 101000.0,
        "avg_36m_market_cap": 68400.0,
        "shares_outstanding": 726600000,
        "pe_ratio": 74.5,
        "pb_ratio": 14.8,
        "dividend_yield": 0.004,
        "last_dividend_per_share": 5.0,
        "total_assets": 11400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 480.0,
        "lease_liabilities": 340.0,
        "total_debt": 820.0,
        "cash_and_bank": 1120.0,
        "current_investments": 940.0,
        "total_cash_and_investments": 2060.0,
        "total_receivables": 2400.0,
        "total_inventories": 2800.0,
        "current_liabilities": 3400.0,
        "operating_revenue": 26820.0,
        "other_income": 280.0,
        "total_revenue": 27100.0,
        "interest_income": 95.0,
        "prohibited_secondary_revenue": 26820.0,
        "total_impermissible_income": 26915.0,
        "filing_date": "2024-05-15",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 16 - Borrowings",
        "cash_note_ref": "Note 10 - Cash & Bank",
        "rec_note_ref": "Note 9 - Trade Receivables",
        "income_note_ref": "Note 23 - Beverage Sales & Interest",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
    {
        "ticker": "RADICO.NS",
        "symbol": "RADICO",
        "isin": "INE944F01028",
        "bse_code": "532497",
        "company_name": "Radico Khaitan Limited",
        "sector": "Consumer Staples",
        "industry": "Distilleries & Alcoholic Beverages",
        "business_summary": "Major Indian alcoholic liquor manufacturer producing Magic Moments vodka, 8PM whisky, and Old Admiral brandy.",
        "current_price": 1820.0,
        "market_cap": 24320.0,
        "avg_36m_market_cap": 16400.0,
        "shares_outstanding": 133600000,
        "pe_ratio": 82.1,
        "pb_ratio": 9.4,
        "dividend_yield": 0.002,
        "last_dividend_per_share": 3.0,
        "total_assets": 4820.0,
        "long_term_debt": 740.0,
        "short_term_debt": 410.0,
        "lease_liabilities": 90.0,
        "total_debt": 1240.0,
        "cash_and_bank": 210.0,
        "current_investments": 180.0,
        "total_cash_and_investments": 390.0,
        "total_receivables": 1120.0,
        "total_inventories": 1280.0,
        "current_liabilities": 1820.0,
        "operating_revenue": 4124.0,
        "other_income": 45.0,
        "total_revenue": 4169.0,
        "interest_income": 12.0,
        "prohibited_secondary_revenue": 4124.0,
        "total_impermissible_income": 4136.0,
        "filing_date": "2024-05-14",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 17 - Borrowings",
        "cash_note_ref": "Note 11 - Cash & Bank",
        "rec_note_ref": "Note 10 - Trade Receivables",
        "income_note_ref": "Note 24 - Liquor Revenue",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 8. NON-COMPLIANT - TOBACCO & NICOTINE (DHARAR)
    # -------------------------------------------------------------
    {
        "ticker": "ITC.NS",
        "symbol": "ITC",
        "isin": "INE154A01025",
        "bse_code": "500875",
        "company_name": "ITC Limited",
        "sector": "Consumer Staples",
        "industry": "Cigarettes, Tobacco, FMCG & Hotels",
        "business_summary": "Multi-business conglomerate where over 70% of operating profit (EBIT) is generated from manufacturing and sale of cigarettes.",
        "current_price": 510.0,
        "market_cap": 637200.0,
        "avg_36m_market_cap": 482000.0,
        "shares_outstanding": 12490000000,
        "pe_ratio": 30.5,
        "pb_ratio": 8.9,
        "dividend_yield": 0.027,
        "last_dividend_per_share": 13.75,
        "total_assets": 88400.0,
        "long_term_debt": 0.0,
        "short_term_debt": 0.0,
        "lease_liabilities": 420.0,
        "total_debt": 420.0,
        "cash_and_bank": 5400.0,
        "current_investments": 12800.0,
        "total_cash_and_investments": 18200.0,
        "total_receivables": 3400.0,
        "total_inventories": 12400.0,
        "current_liabilities": 14200.0,
        "operating_revenue": 76840.0,
        "other_income": 3200.0,
        "total_revenue": 80040.0,
        "interest_income": 1100.0,
        "prohibited_secondary_revenue": 34800.0,  # > 40% of gross revenue from cigarettes
        "total_impermissible_income": 35900.0,
        "filing_date": "2024-05-23",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 19 - Ind AS 116 Lease Obligations",
        "cash_note_ref": "Note 12 - Cash & Current Investments",
        "rec_note_ref": "Note 11 - Trade Receivables",
        "income_note_ref": "Segment Revenue - Cigarettes & Tobacco",
        "is_nifty_50": 1,
        "is_nifty_500": 1,
    },

    # -------------------------------------------------------------
    # 9. NON-COMPLIANT - GAMBLING, CASINOS & REAL-MONEY GAMING (MAYSIR)
    # -------------------------------------------------------------
    {
        "ticker": "DELTACORP.NS",
        "symbol": "DELTACORP",
        "isin": "INE124G01033",
        "bse_code": "532848",
        "company_name": "Delta Corp Limited",
        "sector": "Consumer Discretionary",
        "industry": "Casinos, Gaming & Hospitality",
        "business_summary": "Operates live offshore and onshore casinos in Goa and Sikkim, along with online real-money gaming portals.",
        "current_price": 128.0,
        "market_cap": 3420.0,
        "avg_36m_market_cap": 4820.0,
        "shares_outstanding": 267000000,
        "pe_ratio": 14.8,
        "pb_ratio": 1.4,
        "dividend_yield": 0.010,
        "last_dividend_per_share": 1.25,
        "total_assets": 2740.0,
        "long_term_debt": 0.0,
        "short_term_debt": 40.0,
        "lease_liabilities": 110.0,
        "total_debt": 150.0,
        "cash_and_bank": 410.0,
        "current_investments": 340.0,
        "total_cash_and_investments": 750.0,
        "total_receivables": 95.0,
        "total_inventories": 85.0,
        "current_liabilities": 490.0,
        "operating_revenue": 1024.0,
        "other_income": 45.0,
        "total_revenue": 1069.0,
        "interest_income": 32.0,
        "prohibited_secondary_revenue": 920.0,  # > 85% revenue from casino games of chance
        "total_impermissible_income": 952.0,
        "filing_date": "2024-04-26",
        "reporting_period": "Q4 FY24 Audited Consolidated",
        "source_document": "BSE/NSE Annual Audited Report",
        "debt_note_ref": "Note 14 - Leases",
        "cash_note_ref": "Note 8 - Cash and Bank Balances",
        "rec_note_ref": "Note 7 - Trade Receivables",
        "income_note_ref": "Segment Note - Casino Gaming & Hospitality",
        "is_nifty_50": 0,
        "is_nifty_500": 1,
    },
]


def prepare_company_record(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Calculate all financial ratios, screening statuses, purification, and zakatable assets."""
    record = dict(raw)
    
    # 1. Sector Check
    is_sector_comp, sector_fail_reason = check_sector_compliance(
        sector=record["sector"],
        industry=record["industry"],
        business_summary=record.get("business_summary", ""),
    )
    record["sector_compliant"] = 1 if is_sector_comp else 0
    record["sector_failure_reason"] = sector_fail_reason
    
    # 2. Shariah Dual-Standard Evaluation
    aaoifi_eval, tasis_eval, divergence, div_reason = evaluate_company_shariah(record)
    
    # AAOIFI Fields
    record["aaoifi_debt_ratio"] = aaoifi_eval.debt_ratio.actual_value
    record["aaoifi_cash_ratio"] = aaoifi_eval.cash_ratio.actual_value
    record["aaoifi_rec_ratio"] = aaoifi_eval.receivables_ratio.actual_value
    record["aaoifi_imp_ratio"] = aaoifi_eval.impermissible_income_ratio.actual_value
    record["aaoifi_status"] = aaoifi_eval.status.value
    
    # TASIS Fields
    record["tasis_debt_ratio"] = tasis_eval.debt_ratio.actual_value
    record["tasis_cash_ratio"] = tasis_eval.cash_ratio.actual_value
    record["tasis_rec_ratio"] = tasis_eval.receivables_ratio.actual_value
    record["tasis_imp_ratio"] = tasis_eval.impermissible_income_ratio.actual_value
    record["tasis_status"] = tasis_eval.status.value
    
    # 3. Derived Metrics: Purification & Zakat
    total_rev = float(record["total_revenue"])
    imp_inc = float(record["total_impermissible_income"])
    purif_ratio = round(imp_inc / total_rev, 6) if total_rev > 0 else 0.0
    record["purification_ratio"] = purif_ratio
    
    # Zakatable Net Working Assets per share: (Cash + Rec + Inv - CL) in INR / shares
    znwa_cr = (
        float(record["total_cash_and_investments"])
        + float(record["total_receivables"])
        + float(record.get("total_inventories", 0.0))
        - float(record["current_liabilities"])
    )
    shares = int(record["shares_outstanding"])
    # 1 Cr = 10,000,000 INR
    if shares > 0 and znwa_cr > 0:
        znwa_per_share = round((znwa_cr * 10000000.0) / shares, 2)
    else:
        znwa_per_share = 0.0
    record["zakatable_assets_per_share"] = znwa_per_share
    
    # Audit note summary
    if div_reason:
        record["audit_notes"] = div_reason
    elif not is_sector_comp:
        record["audit_notes"] = f"Failed sector screening: {sector_fail_reason}"
    else:
        record["audit_notes"] = "Screened against audited annual financial statements under AAOIFI & TASIS criteria."

    return record


def seed_database(db_path: str | None = None) -> int:
    """Populate database with pre-seeded representative company universe."""
    init_db(db_path)
    conn = get_db_connection(db_path)
    inserted_count = 0
    
    try:
        cursor = conn.cursor()
        for raw in RAW_COMPANIES_DATA:
            rec = prepare_company_record(raw)
            columns = list(rec.keys())
            placeholders = ", ".join("?" for _ in columns)
            cols_str = ", ".join(columns)
            update_str = ", ".join(f"{col}=excluded.{col}" for col in columns if col != "ticker")
            
            sql = f"""
                INSERT INTO companies ({cols_str})
                VALUES ({placeholders})
                ON CONFLICT(ticker) DO UPDATE SET {update_str};
            """
            cursor.execute(sql, [rec[c] for c in columns])
            inserted_count += 1
            
        # Rebuild FTS5 search index
        cursor.execute("INSERT INTO companies_fts(companies_fts) VALUES('rebuild');")
        conn.commit()
        logger.info(f"Successfully seeded {inserted_count} companies into database.")
    finally:
        conn.close()
        
    return inserted_count


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    count = seed_database()
    print(f"Seeded {count} companies.")
