# QuantOS Daily Automated Git Commit, Sync, and Push Script
# Runs daily to checkpoint machine-generated evidence to the private GitHub repository.
#
# This task stages an ALLOWLIST of paths it owns. It used to run `git add -A`, which is a direct
# violation of PROTOCOL section 4 ("Do not use `git add -A` or broad commits in a shared checkout.
# Stage explicit owned paths only") and which did real damage:
#
#   * 3d120730 swept 2,381 lines of another agent's in-progress source -- src/quant_system/data/
#     universe.py, execution/paper_pilot.py, modeling/mizan_model.py, server/app.py and a test file
#     -- into an automated commit and pushed it to main.
#   * 41a93f60 committed a Red Team brief and work record minutes after they were written, while
#     they were still being edited.
#
# The sharpest case is a Red Team run: mutants are deliberately broken guards applied to the tree
# for seconds at a time. A 23:00 sweep landing mid-mutation commits a disabled safety check to main
# and pushes it, with every test still green -- because that is what a surviving mutant means.
#
# An allowlist rather than a denylist: a denylist silently starts sweeping whatever new top-level
# directory somebody adds next.

param(
    [switch]$Force
)

$ErrorActionPreference = "Continue"
$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
Set-Location $projectRoot

# Paths this automation owns. Everything here is machine-generated by ingestion and authority
# builders, so no agent hand-edits it mid-task and an automatic checkpoint cannot truncate work in
# progress. Adding a path here asserts that nothing edits it by hand.
#
# Deliberately NOT owned, and why:
#   src/, scripts/, tests/   engineering work; where Red Team mutants live
#   .launch/                 release state and adjudication reports, written mid-task
#   agent_context/           work records and path claims, written mid-task
#   pyproject.toml, uv.lock, .gitignore, root guidance
#                            PROTOCOL section 4 names these as single-owner coordination files
$OwnedPaths = @(
    "data/evidence",
    "data/authorities"
)

$logsDir = Join-Path $projectRoot "logs"
if (-not (Test-Path -LiteralPath $logsDir)) {
    New-Item -ItemType Directory -Path $logsDir -Force | Out-Null
}
$logFile = Join-Path $logsDir "auto_sync.log"

function Write-Log {
    param([string]$Message)
    $timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
    $line = "[$timestamp] $Message"
    Write-Host $line
    Add-Content -Path $logFile -Value $line -Encoding utf8
}

function Test-PathIsOwned {
    param([string]$RepoPath)
    foreach ($owned in $OwnedPaths) {
        if ($RepoPath -eq $owned -or $RepoPath.StartsWith("$owned/")) {
            return $true
        }
    }
    return $false
}

Write-Log "=== Starting QuantOS Daily Auto-Sync ==="
Write-Log "Owned paths: $($OwnedPaths -join ', ')"

# 1. Verify Git repository and remote
$remoteUrl = git config --get remote.origin.url
if (-not $remoteUrl) {
    Write-Log "ERROR: No git remote 'origin' configured. Aborting sync."
    exit 1
}
Write-Log "Remote origin: $remoteUrl"

# 2. Fetch latest changes from remote
Write-Log "Fetching remote changes..."
git fetch origin main
if ($LASTEXITCODE -ne 0) {
    Write-Log "ERROR: git fetch failed with exit code $LASTEXITCODE. Aborting sync."
    exit 1
}

# 3. Separate what this task owns from what it must not touch.
#
# Porcelain v1 lines are "XY path". A rename carries "orig -> new"; the destination decides
# ownership, and a rename is only ever staged deliberately by a person anyway.
$statusLines = @(git status --porcelain)
$ownedChanges = @()
$foreignChanges = @()
foreach ($line in $statusLines) {
    if (-not $line.Trim()) { continue }
    $repoPath = $line.Substring(3).Trim().Trim('"')
    if ($repoPath -match ' -> ') { $repoPath = ($repoPath -split ' -> ')[-1].Trim().Trim('"') }
    if (Test-PathIsOwned $repoPath) { $ownedChanges += $line } else { $foreignChanges += $line }
}

Write-Log "Changes in owned paths: $($ownedChanges.Count); left alone: $($foreignChanges.Count)"
if ($foreignChanges.Count -gt 0) {
    Write-Log "Not staged -- these belong to whoever is working on them:"
    foreach ($line in $foreignChanges) { Write-Log "  $line" }
}

# 4. Stage and commit ONLY the owned paths.
if ($ownedChanges.Count -gt 0) {
    Write-Log "Staging owned paths..."
    git add -- $OwnedPaths
    if ($LASTEXITCODE -ne 0) {
        Write-Log "ERROR: git add failed with exit code $LASTEXITCODE. Aborting before commit."
        exit 1
    }

    # An allowlist can stage nothing even when the paths reported changes -- a file matched by
    # .gitignore, for instance. Committing then creates an empty checkpoint every night.
    git diff --staged --quiet
    if ($LASTEXITCODE -eq 0) {
        Write-Log "Nothing staged after add; no commit created."
    } else {
        $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")
        $commitMsg = "sync: evidence checkpoint [$timestamp]"
        Write-Log "Creating commit: $commitMsg"
        git commit -m $commitMsg
        if ($LASTEXITCODE -ne 0) {
            Write-Log "ERROR: git commit failed with exit code $LASTEXITCODE."
            exit 1
        }
    }
} else {
    Write-Log "No changes in owned paths. Nothing to commit."
}

# 5. Integrate and push.
#
# `git pull --rebase --autostash` was removed along with the broad staging that made it survivable.
# Once other agents' work is deliberately left uncommitted, autostash stashes THEIR files, rebases,
# and pops them back.
#
# Measured rather than asserted, because a first draft of this comment overstated it. Driven in a
# throwaway repo, remote and local both editing `src/quant_system/guard.py`, local uncommitted:
#
#   old (autostash, no guard) : exit 0   conflict markers written into guard.py, `UU` in the index
#   new (guard, no autostash) : exit 3   guard.py untouched, no markers
#
# The work is not *lost* either way -- the earlier claim that it was is withdrawn. What actually
# happens is worse in a quieter way: the agent's own source file gets conflict markers written into
# it by a background task, and the task exits 0 reporting success. Nobody is told. Where the
# incoming commits touch different files the pop is clean, so this only bites on real overlap --
# which is exactly the case a nightly job cannot predict.
#
# So: rebase only when nothing foreign is at risk, and otherwise defer. Deferring costs one night
# of backup.
$behind = [int](@(git rev-list --count HEAD..origin/main)[0])
if ($LASTEXITCODE -ne 0) {
    Write-Log "ERROR: could not compare against origin/main (exit $LASTEXITCODE)."
    exit 1
}

if ($behind -gt 0) {
    if (($foreignChanges.Count -gt 0) -and (-not $Force)) {
        Write-Log "DEFERRED: $behind commit(s) behind origin/main with $($foreignChanges.Count) uncommitted change(s) outside owned paths."
        Write-Log "Rebasing would stash and re-apply work this task does not own. Resolve by hand, or re-run with -Force."
        exit 3
    }
    Write-Log "Rebasing onto origin/main ($behind commit(s) behind)..."
    git pull --rebase origin main
    if ($LASTEXITCODE -ne 0) {
        Write-Log "ERROR: rebase failed with exit code $LASTEXITCODE. Leaving the tree for a human; not pushing."
        exit 4
    }
}

$ahead = [int](@(git rev-list --count origin/main..HEAD)[0])
if ($ahead -eq 0) {
    Write-Log "Nothing to push; local main matches origin/main."
    Write-Log "=== QuantOS Daily Auto-Sync Completed Successfully ==="
    exit 0
}

Write-Log "Pushing $ahead commit(s) to origin main..."
git push origin main
if ($LASTEXITCODE -eq 0) {
    Write-Log "=== QuantOS Daily Auto-Sync Completed Successfully ==="
    exit 0
} else {
    Write-Log "WARNING: Push exited with code $LASTEXITCODE"
    exit $LASTEXITCODE
}
